apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: APP_NAME
  namespace: NAMESPACE
  name: deployment
spec:
  selector:
    matchLabels:
      app: APP_NAME
  replicas: 3
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
        - name: APP_NAME      
          image: image-name
          imagePullPolicy: Always
          env:
          - name: DOT_BOOKS_AWS_REGION
            value: "ap-south-1"
          - name: DOT_BOOKS_CONFIG_BUCKET
            value: "dot-books-config-dev"
          - name: PLATFORM_VERSION
            value: "dev"
          - name: AWS_NODEJS_CONNECTION_REUSE_ENABLED
            value: "1"
          - name: PUPPETEER_EXECUTABLE_PATH
            value: "/usr/bin/google-chrome"
      #     volumeMounts:
      #       - name: varlibdockercontainers
      #         mountPath: /var/log/containers
      #     readinessProbe:
      #       httpGet:
      #         path: /heartbeat
      #         port: 8020
      #       initialDelaySeconds: 10
      #       timeoutSeconds: 5
      #       periodSeconds: 3
      #       failureThreshold: 5
      #     livenessProbe:
      #       httpGet:
      #         path: /heartbeat
      #         port: 8020
      #       initialDelaySeconds: 10
      #       timeoutSeconds: 5
      #       periodSeconds: 3
      #       failureThreshold: 5
      # volumes: 
      #   - name: varlibdockercontainers
      #     hostPath:
      #       path: /var/log/containers


