apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: APP_NAME                      # Placeholder
  namespace: NAMESPACE                 # Placeholder
  name: DEPLOYMENT_NAME                # Placeholder
spec:
  selector:
    matchLabels:
      app: APP_NAME                     # Placeholder
  replicas: REPLICAS                    # Placeholder
  template:
    metadata:
      labels:
        app: APP_NAME                  # Placeholder
    spec:
      containers:
        - image: IMAGE_NAME             # Placeholder
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "Asia/Kolkata"
          name: APP_NAME                # Placeholder
