apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: APP_NAME
