apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dot-books-onboard                      
  namespace: argocd                 
  name: deployment                
spec:
  selector:
    matchLabels:
      app: dot-books-onboard                     
  replicas: 1                    
  template:
    metadata:
      labels:
        app: dot-books-onboard                    
    spec:
      containers:
        - image: IMAGE_NAME
          env:
          name: dot-books-onboard
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            




