apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dot-books-onboard                      
  namespace: argocd                 
  name: deployment                
spec:
  selector:
    matchLabels:
      app: dot-books-onboard                     
  replicas: 1                    
  template:
    metadata:
      labels:
        app: dot-books-onboard                    
    spec:
      containers:
        - name: app-name               
          image: nginx:latest            
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "Asia/Kolkata"
          name: dot-books-onboard