apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namePrefix: dev-dot-books-onboard- 

resources:
  - ../../../base/frontend 


patches:
  - target:
      kind: Deployment
      name: deployment 
    path: deployment-patch.yaml

  - target:
      kind: Service
      name: service 
    path: service-patch.yaml
