apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dot-books-onboard- 

resources:
  - ../../../base/frontend 

patches:
  - target:
      kind: Deployment
      name: dot-books-onboard 
    path: deployment-patch.yaml

  - target:
      kind: Service
      name: dot-books-onboard 
    path: service-patch.yaml
