apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-dot-books-onboard- 

resources:
  - ../../../base/frontend 

images:
  - name: IMAGE_NAME
    newName: 533267268220.dkr.ecr.ap-south-1.amazonaws.com/dot-books/dot-books-onboard
    newTag: IMG_TAG

patches:
  - target:
      kind: Deployment
      name: dot-books-onboard 
    path: deployment-patch.yaml

  - target:
      kind: Service
      name: dot-books-onboard 
    path: service-patch.yaml
