apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend 

patches:
  - target:
      kind: Deployment
      name: dot-common 
    path: deployment-patch.yaml

