apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sales-batch-email
  namespace: argocd
  name: sales-batch-email
spec:
  selector:
    matchLabels:
      app: sales-batch-email
  replicas: 2
  template:
    metadata:
      labels:
        app: sales-batch-email
    spec:
      containers:
        - name: app-name      
          image: 533267268220.dkr.ecr.ap-south-1.amazonaws.com/dot-books/sales-batch:IMG_TAG
          imagePullPolicy: Always
          env:
          - name: BATCHSERVICE
            value: "email"
          volumeMounts:
            - name: sales-batch-email-node-logs
              mountPath: /var/log/node
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8020
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8020
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 5
          name: sales-batch-email
      volumes: 
        - name: sales-batch-email-node-logs
          nfs:
            path: /dot-books/dev/sales-batch-email/node
            server: fs-070479e27c7cd87d2.efs.ap-south-1.amazonaws.com



