apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-sales-batch-email- 

resources:
  - ../../../base/backend 


# patches:
#   - target:
#       kind: Deployment
#       name: deployment 
#     path: deployment-patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: deployment
    path: patch-deployment.yaml